/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'canvas-base': '#ffffff',
        'canvas-soft': '#fafafa',
        'surface': '#f8f9ff',
        'surface-card': '#ffffff',
        'surface-subtle': '#f0f0f3',
        'surface-dark': '#171717',
        'surface-dark-elevated': '#1a1a1a',
        'surface-dim': '#d7dae3',
        'surface-variant': '#dfe2ec',
        'surface-container': '#ebeef7',
        'surface-container-low': '#f0f3fd',
        'surface-container-high': '#e5e8f1',
        'surface-container-highest': '#dfe2ec',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f8f9ff',
        'surface-tint': '#5f5e5e',
        'text-ink': '#171717',
        'text-body': '#60646c',
        'text-muted': '#999999',
        'text-disabled': '#cccccc',
        'text-on-dark': '#ffffff',
        'text-on-dark-muted': '#b0b4ba',
        'hairline-default': '#f0f0f3',
        'hairline-soft': '#f5f5f7',
        'hairline-strong': '#dcdee0',
        'outline': '#747878',
        'outline-variant': '#c4c7c7',
        'cta-black': '#000000',
        'cta-black-active': '#1a1a1a',
        'primary': '#000000',
        'on-primary': '#ffffff',
        'secondary': '#005fad',
        'on-secondary': '#ffffff',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'semantic-active': '#16a34a',
        'semantic-active-surface': '#f0fdf4',
        'semantic-active-border': '#bbf7d0',
        'semantic-risk': '#ab6400',
        'semantic-risk-accent': '#f59e0b',
        'semantic-risk-surface': '#fffbeb',
        'semantic-risk-border': '#fde68a',
        'semantic-churned': '#e11d48',
        'semantic-churned-accent': '#eb8e90',
        'semantic-churned-surface': '#fff1f2',
        'semantic-churned-border': '#fecdd3',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '20px',
        xl: '24px',
        xxl: '32px',
        'gutter-mobile': '16px',
        'gutter-desktop': '24px',
        'sidebar-width': '240px',
        'bottom-nav-height': '64px',
        'top-nav-height': '56px',
        'form-max-width': '540px',
        'container-max-width': '1200px',
      },
      fontFamily: {
        'display-hero': ['"Hanken Grotesk"'],
        'display-hero-mobile': ['"Hanken Grotesk"'],
        'headline-lg': ['"Hanken Grotesk"'],
        'headline-md': ['"Hanken Grotesk"'],
        'headline-sm': ['"Hanken Grotesk"'],
        'numeric-stat': ['"Hanken Grotesk"'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'body-strong': ['Inter'],
        'button': ['Inter'],
        'caption': ['Inter'],
        'caption-uppercase': ['Inter'],
      },
      fontSize: {
        'display-hero': ['36px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'display-hero-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'numeric-stat': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '21px', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0', fontWeight: '400' }],
        'body-strong': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '600' }],
        'button': ['14px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '500' }],
        'caption': ['12px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '400' }],
        'caption-uppercase': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
